# Status e tipos do domínio (valores persistidos em PT)

JOB_STATUS_PENDENTE = "pendente"
JOB_STATUS_EM_EXECUCAO = "em_execucao"
JOB_STATUS_CONCLUIDO = "concluido"
JOB_STATUS_FALHA = "falha"
JOB_STATUS_CANCELADO = "cancelado"

JOB_STATUSES = {
    JOB_STATUS_PENDENTE,
    JOB_STATUS_EM_EXECUCAO,
    JOB_STATUS_CONCLUIDO,
    JOB_STATUS_FALHA,
    JOB_STATUS_CANCELADO,
}

JOB_EXECUTABLE = {JOB_STATUS_PENDENTE, JOB_STATUS_FALHA}

JOB_TIPO_VARREDURA = "varredura_divergencias"

EVENTO_INICIO = "inicio"
EVENTO_PROGRESSO = "progresso"
EVENTO_FIM = "fim"
EVENTO_ERRO = "erro"

ORIGEM_JOB = "job"
ORIGEM_MANUAL = "manual"

INCONSISTENCIA_ABERTA = "aberta"
INCONSISTENCIA_EM_ANALISE = "em_analise"
INCONSISTENCIA_RESOLVIDA = "resolvida"
INCONSISTENCIA_DESCARTADA = "descartada"

INCONSISTENCIA_STATUSES = {
    INCONSISTENCIA_ABERTA,
    INCONSISTENCIA_EM_ANALISE,
    INCONSISTENCIA_RESOLVIDA,
    INCONSISTENCIA_DESCARTADA,
}

INCONSISTENCIA_FECHADAS = {
    INCONSISTENCIA_RESOLVIDA,
    INCONSISTENCIA_DESCARTADA,
}

SEVERIDADE_BAIXA = "baixa"
SEVERIDADE_MEDIA = "media"
SEVERIDADE_ALTA = "alta"

SEVERIDADES = {SEVERIDADE_BAIXA, SEVERIDADE_MEDIA, SEVERIDADE_ALTA}

TIPO_DIVERGENCIA_VALOR = "divergencia_valor"
TIPO_CNPJ_INVALIDO = "cnpj_invalido"
TIPO_CAMPO_OBRIGATORIO = "campo_obrigatorio"

TIPOS_INCONSISTENCIA = {
    TIPO_DIVERGENCIA_VALOR,
    TIPO_CNPJ_INVALIDO,
    TIPO_CAMPO_OBRIGATORIO,
}

PARECER_MIN_CHARS = 10
MAX_INCONSISTENCIAS_POR_EXECUCAO = 20
DEFAULT_QUANTIDADE_VARREDURA = 3
